export const PATH_NAME = {
  ROOT: "/",
  ERROR_404: "/404",
  LOGIN: "/login",
  PRODUCT: "/product",
  PRODUCT_LIST: "/product/list",
  PRODUCT_ADD: "/product/add",
  USER_PROFILE: "/user/profile",
  USER_ORDER: "/user/order",
  CART: "/cart",
  PRODUCT_DETAIL: "/detailProduct/:id",
  ADMIN: "/admin",
  ADMIN_USER: "/admin/users",
  ADMIN_PRODUCT: "/admin/products",
  ADMIN_STATUS: "/admin/status",
  ADMIN_ORDER: "/admin/orders",
};
